FROM alpine:3.8

RUN apk add --update nginx && rm -rf /var/cache/apk/*

COPY sources/nginx.conf /etc/nginx/
COPY sources/index.php /usr/share/nginx/html/
RUN mkdir -p /usr/share/nginx/html

RUN set -x \
    && adduser -u 82 -D -S -G www-data www-data

#RUN chown -R www-data:www-data /usr/share/nginx/html
#RUN chmod u+rwx,g+rx,o+rx /usr/share/nginx/html
#RUN find /usr/share/nginx/html -type d -exec chmod 755 {} +
#RUN find /usr/share/nginx/html -type f -exec chmod 644 {} +
#RUN nginx -t -c /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]